#!/bin/sh

# make sure the widget is
# "custom/athan": {
# "format": "󱠧  {}",
# "exec": "<Path to this file>",
# "interval": 60,
# }

STATUS_PATH="$XDG_RUNTIME_DIR/waybar_athan.status"


prayer=$(~/.cargo/bin/waybar_athan -l 36.54 -L 3.95 -v)
class=$(echo "$prayer" | tail -n 1)
text=$(echo "$prayer"| head -n 1)
name=$(echo "$text" | cut -f1 -d" ")

case "$class" in
  remaining)
    status=0
    ;;
  before)
    status=1
    ;;
  athan)
    status=2
    ;;
  past)
    status=3
    ;;
esac


if ! [ -f "$STATUS_PATH" ]; then
  echo "$name:$status" > "$STATUS_PATH"
fi

old_name=$(cat "$STATUS_PATH" | cut -f1 -d":")

if ! [ "$old_name" = "$name" ]; then
  old_status=0
else
  old_status=$(cat "$STATUS_PATH" | cut -f2 -d":")
fi

if [ "$status" -gt "$old_status" ]; then
  case "$status" in
    1)
      notify-send -u normal -a "Athan Notify" -i "compass" "Athan" "$text"
      ;;
    2)
      notify-send -u critical -a "Athan Notify" -i "compass" "Athan" "$text"
      ;;
  esac
fi

echo "$name:$status" > "$STATUS_PATH"
echo "$prayer"
